spring.application.name=employee-management
spring.profiles.default=dev
spring.jpa.open-in-view=false
spring.cache.cache-names=employeeCount
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=60s,recordStats
management.endpoints.web.exposure.include=health,metrics
